export const presidents = [
  {
    fname: "Anubhav",
    lname: "Pathak",
    role: "PRESIDENT",
    image: "anubhav.jpg",
    github: "Anubhav-Pathak",
    linkedin: "anubhav-pathak-3026a4219/",
  },

  {
    fname: "Nandini",
    lname: "Agrawal",
    role: "VICE PRESIDENT",
    image: "nandini.jpeg",
    mail: "agrawalnandini6@gmail.com",
    linkedin: "nandini-agrawal-851815225/",
  },
  {
    fname: "Pushkar",
    lname: "Tuse",
    role: "VICE PRESIDENT",
    image: "pushkar.jpg",
    mail: "pushkar.tuse@gmail.com",
    linkedin: "pushkar-tuse/",
  },
];

export const board = [
  {
    fname: "Aryan",
    lname: "Raj",
    role: "TECHNICAL DIRECTOR",
    image: "AryanRaj.jpg",
    github: "aryanraj2713",
    linkedin: "https://www.linkedin.com/in/aryanraj13/",
  },
  {
    fname: "Sai Satya ",
    lname: "Narayana",
    role: "TECHNICAL DIRECTOR",
    image: "sai.jpg",
    github: "SaiSatya16",
    linkedin: "https://www.linkedin.com/in/sai-satya-jonnalagadda-157900225/",
  },
  {
    fname: "Pouravi",
    lname: "Pawar",
    role: "CORPORATE DIRECTOR",
    image: "uraviPawar.jpeg",
    github: "",
    linkedin: "pouravi-pawar-6918aa251/",
  },
  {
    fname: "Aditya",
    lname: " Achuthan",
    role: "CORPORATE DIRECTOR",
    image: "Aditya.jpg",
    mail: "ak8421@srmist.edu.in",
    linkedin: "https://www.linkedin.com/in/aditya-achuthan-83abb0220/",
  },
  {
    fname: "Siddharth    ",
    lname: "Singh",
    role: " ASSOC. CORPORATE DIRECTOR",
    image: "Siddharth.jpeg",
    mail: "siddharth77work@gmail.com",
    linkedin: "https://www.linkedin.com/in/siddharth-singh-aa9453260",
  },
  {
    fname: "Zainab ",
    lname: "Zaiba",
    role: "CREATIVES DIRECTOR",
    image: "Zainab.jpg",
    mail: "xynab.02@gmail.com",
    linkedin: "https://in.linkedin.com/in/xynab-zander-35421b285",
  },
  {
    fname: "Parth ",
    lname: "Bhargava",
    role: "CREATIVES DIRECTOR",
    image: "Parth.jpg",
    mail: "pb3958@srmist.edu.in",
    linkedin: "https://www.linkedin.com/in/parth-bhargava-ba7118249/",
  },
  {
    fname: "Viknesh",
    lname: "S",
    role: "RESEARCH DIRECTOR",
    image: "Viknesh.jpeg",
    github: "VIKNESH1211",
    linkedin: "https://www.linkedin.com/in/viknesh-s-2a20a9218/",
  },
  {
    fname: "Zayed Syed",
    lname: "Haque",
    role: "PROJECTS DIRECTOR",
    image: "Zayed.jpg",
    github: "zayed-haque",
    linkedin: "https://www.linkedin.com/in/zayed-haque/",
  },
];

export const advisor = [
  {
    fname: "Anush",
    lname: "Bhatia",
    role: "TECHNICAL ADVISOR",
    image: "anush.jpg",
    github: "anushbhatia",
    linkedin: "anush-bhatia-aa500a158",
  },
  {
    fname: "Avirup",
    lname: "Chattaraj",
    role: "TECHNICAL ADVISOR",
    image: "avirup.jpg",
    github: "severussnape123",
    linkedin: "avirupchattaraj",
  },
  {
    fname: "Hritik",
    lname: "Bhandari",
    role: "TECHNICAL ADVISOR",
    image: "hritik.jpg",
    github: "hritikbhandari",
    linkedin: "hritikbhandari",
  },

  {
    fname: "Pratyaksh",
    lname: "Bhalla",
    role: "TECHNICAL ADVISOR",
    image: "pratyaksh.jpg",
    github: "pratyaksh64",
    linkedin: "pratyaksh-bhalla-96871b186",
  },
  {
    fname: "Takshil",
    lname: " Mittal",
    role: "EVENTS ADVISOR",
    image: "takshil.jpg",
    github: "takshilmittal",
    linkedin: "takshil-mittal",
  },
  {
    fname: "Akshat",
    lname: "Anand",
    role: "PROJECTS ADVISOR",
    image: "akshat.jpg",
    github: "cipheraxat",
    linkedin: "akshatanand1999",
  },
  {
    fname: "Gayathri",
    lname: "Seetharaman",
    role: "R&D ADVISOR",
    image: "gayathri.jpg",
    github: "Gayathri621",
    linkedin: "gayathri-seetharaman-964986158",
  },
  {
    fname: "Shubhangi",
    lname: "Soni",
    role: "CORPORATE ADVISOR",
    image: "shubhangi.jpeg",
    github: "ShubhangiSoni1603",
    linkedin: "shubhangi-soni",
  },
  {
    fname: "Soumya",
    lname: "Kundu",
    role: "EDITORIAL ADVISOR",
    image: "soumya.jpeg",
    github: "aymuos15",
    linkedin: "soumya-snigdha-kundu-84b812183",
  },
  {
    fname: "Stuti",
    lname: "Sehgal",
    role: "TECHNICAL ADVISOR",
    image: "stuti.jpg",
    github: "stutisehgal",
    linkedin: "stuti-sehgal-7a10301b1",
  },
  {
    fname: "Ishika",
    lname: "Gupta",
    role: "PUBLIC RELATIONS ADVISOR",
    image: "ishika.jpg",
    mail: "ishikag2050@gmail.com",
    linkedin: "findishika",
  },
  {
    fname: "Sheel",
    lname: "Patel",
    role: "TECHNICAL ADVISOR",
    image: "sheel.jpg",
    github: "sheel1206",
    linkedin: "sheel1206",
  },
  {
    fname: "Shaswat",
    lname: "Srivastava",
    role: "TECHNICAL ADVISOR",
    image: "shaswat.jpeg",
    github: "shaas1704",
    linkedin: "shaswat-srivastava-03a67118b/",
  },
  {
    fname: "Rakesh",
    lname: "J",
    role: "PROJECTS ADVISOR",
    image: "rakesh j.jpg",
    github: "stagnito",
    linkedin: "rakesh-j-35174618b",
  },
  {
    fname: "Aarsh",
    lname: "Chaube",
    role: "R&D ADVISOR",
    image: "aarsh.jpg",
    github: "Aarsh2001",
    linkedin: "aarsh-chaube-0099521a1",
  },
  {
    fname: "Udit",
    lname: "Dhawan",
    role: "CORPORATE ADVISOR",
    image: "udit.jpg",
    github: "udit2812",
    linkedin: "udit-dhawan-819762166/",
  },
  {
    fname: "Abhimanyu",
    lname: "Bhadauria",
    role: "CREATIVES ADVISOR",
    image: "abhimanyu.png",
    github: "Mnayu",
    linkedin: "abhimanyu2911",
  },
  {
    fname: "Shubhank",
    lname: "Sargam",
    role: "CREATIVES ADVISOR",
    image: "shubhank.jpg",
    github: "shubhanksargam",
    linkedin: "shubhanks/",
  },
  {
    fname: "Ankit",
    lname: "Hans",
    role: "TECHNICAL ADVISOR",
    image: "ankit.jpeg",
    github: "ankithans",
    linkedin: "ankithans",
  },
  {
    fname: "Palak",
    lname: "Aggarwal",
    role: "TECHNICAL ADVISOR",
    image: "palak.jpeg",
    github: "Palak-Aggarwal1234",
    linkedin: "palak-aggarwal-96366a18b/",
  },
  {
    fname: "Abhay",
    lname: "Lal",
    role: "COMMUNITY ADVISOR",
    image: "abhay.jpeg",
    github: "abhay-lal",
    linkedin: "abhay-l-6850111bb/",
  },
  {
    fname: "Aadit",
    lname: "Bhargawa",
    role: "COMMUNITY ADVISOR",
    image: "aadit.png",
    github: "",
    linkedin: "aadit-bhargava-b58507200/",
  },
  {
    fname: "Kruthi",
    lname: "M",
    role: "TECHNICAL ADVISOR",
    image: "kruthi.jpeg",
    github: "Kruthim1304",
    linkedin: "kruthi-m-49b300200/",
  },
  {
    fname: "Arun",
    lname: "Jangra",
    role: "TECHNICAL ADVISOR",
    image: "arun.jpeg",
    github: "Arun89-crypto",
    linkedin: "arun-jangra-4a94b41b5/",
  },
  {
    fname: "Tanmay",
    lname: "Agrawal",
    role: "PROJECTS ADVISOR",
    image: "tanmay.jpg",
    github: "Vector3103",
    linkedin: "tanmay-agrawal-b685531b0",
  },
  {
    fname: "Tanisha",
    lname: "Kapoor",
    role: "CREATIVES ADVISOR",
    image: "tanisha.jpg",
    github: "tanishakapoor11",
    linkedin: "tanisha-kapoor-4713261a0/",
  },
  {
    fname: "Surya",
    lname: "Reddy",
    role: "CORPORATE ADVISOR",
    image: "surya.jpeg",
    github: "",
    linkedin: "gnana-surya-teja-reddy/",
  },
  {
    fname: "Jahnavi",
    lname: "Darbhamulla",
    role: "TECHNICAL ADVISOR",
    image: "jahnavi.jpg",
    github: "JahnaviDarbhamulla",
    linkedin: "jahnavi-darbhamulla-0a4280201/",
  },
  {
    fname: "Swapnil",
    lname: "Sinha",
    role: "CORPORATE ADVISOR",
    image: "swapnilSinha.jpg",
    github: "",
    linkedin: "swapnilsinha81/",
  },
];

export const techmembers = [
  {
    fname: "Trisha Sharan",
    lname: "Thakur",
    role: "Web Supervisor",
    image: "trishaThakur.jpeg",
    github: "trisha-thakur",
    linkedin: "linkedin.com/in/trisha-s-thakur ",
  },
  {
    fname: "Sahiti",
    lname: "Naidu",
    role: "AI/ML Supervisor",
    image: "sahiti.jpg",
    github: "Sahitihas",
    linkedin:
      "https://www.linkedin.com/in/sahiti-naidu-8a577321a/?originalSubdomain=in",
  },
  {
    fname: "Animesh",
    lname: "Raj",
    role: "AI/ML Supervisor",
    image: "animesh.jpg",
    github: "AnimeshR22",
    linkedin: "https://www.linkedin.com/in/animesh-raj-631646226/",
  },
];
export const research = [
  {
    fname: "Vaishnav",
    lname: "MK",
    role: "Research Supervisor",
    image: "vaishnav.jpg",
    github: "vaishnav-mk",
    linkedin: "https://www.linkedin.com/in/vaishnav-mk",
  },
];
export const designmembers = [
  {
    fname: "R Dheraj",
    lname: "Krishna",
    role: "GFX Supervisor",
    image: "dheeraj.JPG",
    mail: "dherajrock@gmail.com",
    linkedin:
      "https://www.linkedin.com/in/dheraj-krishna-025965256?trk=contact-info",
  },
  {
    fname: "Devi Sri Priya ",
    lname: "Nandepu  ",
    role: "UI/UX Supervisor",
    image: "Priya.jpeg",
    mail: "priyanandepu@gmail.com",
    linkedin: "https://www.linkedin.com/in/priya-n-502995218",
  },
];

export const mgmtmembers = [
  {
    fname: "Rajeev ",
    lname: "Daga ",
    role: "Sponsorship Supervisor",
    image: "Rajeev.jpg",
    mail: "rajeevdaga2004@gmail.com",
    linkedin: "https://www.linkedin.com/in/rajeev-daga-21932322b",
  },
  {
    fname: "Ranga Ananta ",
    lname: " Vatsalya Rama",
    role: "Sponsorship Supervisor",
    image: "ranga.jpg",
    mail: "anantavatsalyaramaranga@gmail.com",
    linkedin:
      "https://www.linkedin.com/in/ananta-vatsalya-rama-ranga-337294251",
  },
  {
    fname: "Misha ",
    lname: "Goyal ",
    role: "Content Supervisor",
    image: "misha.jpg",
    mail: "goyalmisha04@gmail.com",
    linkedin: "http://linkedin.com/in/misha-goyal-910a28246",
  },
  {
    fname: "Riya ",
    lname: "Agarwal ",
    role: "Content Supervisor",
    image: "riya.png",
    mail: "r180503a@gmail.com",
    linkedin: "https://www.linkedin.com/in/riya-agarwal-013046225/",
  },
  {
    fname: "Soham Singh",
    lname: "Thakur",
    role: "Events & PR Supervisor",
    image: "soham.jpg",
    mail: "goyalmisha04@gmail.com",
    linkedin: "http://linkedin.com/in/misha-goyal-910a28246",
  },
  {
    fname: "Ridhi",
    lname: "Lala",
    role: "Events & PR Supervisor",
    image: "ridhi.jpg",
    mail: "ridhilala0905@gmail.com",
    linkedin: "https://www.linkedin.com/in/ridhi-lala-056655249",
  },
  {
    fname: "Dev Pratap ",
    lname: "Singh",
    role: "Events & PR Supervisor",
    image: "dev.jpg",
    mail: "devsogarwal03@gmail.com",
    linkedin: "https://www.linkedin.com/in/dev-pratap-singh-829885223/",
  },
];
