export const presidents = [];

export const board = [
  {
    fname: "Anubhav",
    lname: "Pathak",
    role: "PRESIDENT",
    image: "anubhav.jpg",
    github: "Anubhav-Pathak",
    linkedin: "anubhav-pathak-3026a4219/",
  },

  {
    fname: "Nandini",
    lname: "Agrawal",
    role: "VICE PRESIDENT",
    image: "nandini.jpeg",
    mail: "agrawalnandini6@gmail.com",
    linkedin: "nandini-agrawal-851815225/",
  },
  {
    fname: "Pushkar",
    lname: "Tuse",
    role: "VICE PRESIDENT",
    image: "pushkar.jpg",
    mail: "pushkar.tuse@gmail.com",
    linkedin: "pushkar-tuse/",
  },
  {
    fname: "Pouravi",
    lname: "Pawar",
    role: "CORPORATE DIRECTOR",
    image: "uraviPawar.jpeg",
    github: "",
    linkedin: "pouravi-pawar-6918aa251/",
  },
];

export const advisor = [
  {
    fname: "Anush",
    lname: "Bhatia",
    role: "TECHNICAL ADVISOR",
    image: "anush.jpg",
    github: "anushbhatia",
    linkedin: "anush-bhatia-aa500a158",
  },
  {
    fname: "Avirup",
    lname: "Chattaraj",
    role: "TECHNICAL ADVISOR",
    image: "avirup.jpg",
    github: "severussnape123",
    linkedin: "avirupchattaraj",
  },
  {
    fname: "Hritik",
    lname: "Bhandari",
    role: "TECHNICAL ADVISOR",
    image: "hritik.jpg",
    github: "hritikbhandari",
    linkedin: "hritikbhandari",
  },

  {
    fname: "Pratyaksh",
    lname: "Bhalla",
    role: "TECHNICAL ADVISOR",
    image: "pratyaksh.jpg",
    github: "pratyaksh64",
    linkedin: "pratyaksh-bhalla-96871b186",
  },
  {
    fname: "Takshil",
    lname: " Mittal",
    role: "EVENTS ADVISOR",
    image: "takshil.jpg",
    github: "takshilmittal",
    linkedin: "takshil-mittal",
  },
  {
    fname: "Akshat",
    lname: "Anand",
    role: "PROJECTS ADVISOR",
    image: "akshat.jpg",
    github: "cipheraxat",
    linkedin: "akshatanand1999",
  },
  {
    fname: "Gayathri",
    lname: "Seetharaman",
    role: "RESEARCH & DEVELOPMENT ADVISOR",
    image: "gayathri.jpg",
    github: "Gayathri621",
    linkedin: "gayathri-seetharaman-964986158",
  },
  {
    fname: "Shubhangi",
    lname: "Soni",
    role: "CORPORATE ADVISOR",
    image: "shubhangi.jpeg",
    github: "ShubhangiSoni1603",
    linkedin: "shubhangi-soni",
  },
  {
    fname: "Soumya",
    lname: "Kundu",
    role: "EDITORIAL ADVISOR",
    image: "soumya.jpeg",
    github: "aymuos15",
    linkedin: "soumya-snigdha-kundu-84b812183",
  },
  {
    fname: "Stuti",
    lname: "Sehgal",
    role: "TECHNICAL ADVISOR",
    image: "stuti.jpg",
    github: "stutisehgal",
    linkedin: "stuti-sehgal-7a10301b1",
  },
  {
    fname: "Ishika",
    lname: "Gupta",
    role: "PUBLIC RELATIONS ADVISOR",
    image: "ishika.jpg",
    mail: "ishikag2050@gmail.com",
    linkedin: "findishika",
  },
  {
    fname: "Sheel",
    lname: "Patel",
    role: "TECHNICAL ADVISOR",
    image: "sheel.jpg",
    github: "sheel1206",
    linkedin: "sheel1206",
  },
  {
    fname: "Shaswat",
    lname: "Srivastava",
    role: "TECHNICAL ADVISOR",
    image: "shaswat.jpeg",
    github: "shaas1704",
    linkedin: "shaswat-srivastava-03a67118b/",
  },
  {
    fname: "Rakesh",
    lname: "J",
    role: "PROJECTS ADVISOR",
    image: "rakesh j.jpg",
    github: "stagnito",
    linkedin: "rakesh-j-35174618b",
  },
  {
    fname: "Aarsh",
    lname: "Chaube",
    role: "RESEARCH & DEVELOPMENT ADVISOR",
    image: "aarsh.jpg",
    github: "Aarsh2001",
    linkedin: "aarsh-chaube-0099521a1",
  },
  {
    fname: "Udit",
    lname: "Dhawan",
    role: "CORPORATE ADVISOR",
    image: "udit.jpg",
    github: "udit2812",
    linkedin: "udit-dhawan-819762166/",
  },
  {
    fname: "Abhimanyu",
    lname: "Bhadauria",
    role: "CREATIVES ADVISOR",
    image: "abhimanyu.png",
    github: "Mnayu",
    linkedin: "abhimanyu2911",
  },
  {
    fname: "Shubhank",
    lname: "Sargam",
    role: "CREATIVES ADVISOR",
    image: "shubhank.jpg",
    github: "shubhanksargam",
    linkedin: "shubhanks/",
  },
  {
    fname: "Ankit",
    lname: "Hans",
    role: "TECHNICAL ADVISOR",
    image: "ankit.jpeg",
    github: "ankithans",
    linkedin: "ankithans",
  },
  {
    fname: "Palak",
    lname: "Aggarwal",
    role: "TECHNICAL ADVISOR",
    image: "palak.jpeg",
    github: "Palak-Aggarwal1234",
    linkedin: "palak-aggarwal-96366a18b/",
  },
  {
    fname: "Abhay",
    lname: "Lal",
    role: "COMMUNITY ADVISOR",
    image: "abhay.jpeg",
    github: "abhay-lal",
    linkedin: "abhay-l-6850111bb/",
  },
  {
    fname: "Aadit",
    lname: "Bhargawa",
    role: "COMMUNITY ADVISOR",
    image: "aadit.png",
    github: "",
    linkedin: "aadit-bhargava-b58507200/",
  },
  {
    fname: "Kruthi",
    lname: "M",
    role: "TECHNICAL ADVISOR",
    image: "kruthi.jpeg",
    github: "Kruthim1304",
    linkedin: "kruthi-m-49b300200/",
  },
  {
    fname: "Arun",
    lname: "Jangra",
    role: "TECHNICAL ADVISOR",
    image: "arun.jpeg",
    github: "Arun89-crypto",
    linkedin: "arun-jangra-4a94b41b5/",
  },
  {
    fname: "Tanmay",
    lname: "Agrawal",
    role: "PROJECTS ADVISOR",
    image: "tanmay.jpg",
    github: "Vector3103",
    linkedin: "tanmay-agrawal-b685531b0",
  },
  {
    fname: "Tanisha",
    lname: "Kapoor",
    role: "CREATIVES ADVISOR",
    image: "tanisha.jpg",
    github: "tanishakapoor11",
    linkedin: "tanisha-kapoor-4713261a0/",
  },
  {
    fname: "Surya",
    lname: "Reddy",
    role: "CORPORATE ADVISOR",
    image: "surya.jpeg",
    github: "",
    linkedin: "gnana-surya-teja-reddy/",
  },
  {
    fname: "Jahnavi",
    lname: "Darbhamulla",
    role: "TECHNICAL ADVISOR",
    image: "jahnavi.jpg",
    github: "JahnaviDarbhamulla",
    linkedin: "jahnavi-darbhamulla-0a4280201/",
  },
  {
    fname: "Swapnil",
    lname: "Sinha",
    role: "CORPORATE ADVISOR",
    image: "swapnilSinha.jpg",
    github: "",
    linkedin: "swapnilsinha81/",
  },
];

export const techmembers = [
  {
    fname: "Trisha Sharan",
    lname: "Thakur",
    role: "Web Supervisor",
    image: "trishaThakur.jpeg",
    github: "trisha-thakur",
    linkedin: "linkedin.com/in/trisha-s-thakur ",
  },
  {
    fname: "Sahiti",
    lname: "Naidu",
    role: "AI/ML Supervisor",
    image: "sahiti.jpg",
    github: "Sahitihas",
    linkedin:
      "https://www.linkedin.com/in/sahiti-naidu-8a577321a/?originalSubdomain=in",
  },
  {
    fname: "Animesh",
    lname: "Raj",
    role: "AI/ML Supervisor",
    image: "animesh.jpg",
    github: "AnimeshR22",
    linkedin: "https://www.linkedin.com/in/animesh-raj-631646226/",
  },
];

export const designmembers = [
  // {
  //     fname: "Syed",
  //     lname: "Amaan Ariz",
  //     role: "Designer",
  //     image: "syed.jpg",
  //     github: "SYEDAMAAN05",
  //     linkedin: "syed-amaan-430a7b1b2",
  // },
];

export const mgmtmembers = [
  {
    fname: "Rajeev ",
    lname: "Daga ",
    role: "Sponsorship Supervisor",
    image: "Rajeev.jpg",
    mail: "rajeevdaga2004@gmail.com",
    linkedin: "https://www.linkedin.com/in/rajeev-daga-21932322b",
  },
  {
    fname: "Misha ",
    lname: "Goyal ",
    role: "Content Supervisor",
    image: "misha.jpg",
    mail: "goyalmisha04@gmail.com",
    linkedin: "http://linkedin.com/in/misha-goyal-910a28246",
  },
  {
    fname: "Soham Singh",
    lname: "Thakur",
    role: "Events & PR Supervisor",
    image: "soham.jpg",
    mail: "goyalmisha04@gmail.com",
    linkedin: "http://linkedin.com/in/misha-goyal-910a28246",
  },
];
